services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8099:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - wp_data:/var/www/html
      - ../build/wp-content/themes/rescate-vertical:/var/www/html/wp-content/themes/rescate-vertical
      - ../build/wp-content/plugins/rescate-vertical-tools:/var/www/html/wp-content/plugins/rescate-vertical-tools

  cli:
    image: wordpress:cli
    depends_on:
      - db
      - wordpress
    user: "33:33"
    volumes:
      - wp_data:/var/www/html
      - ../build/wp-content/themes/rescate-vertical:/var/www/html/wp-content/themes/rescate-vertical
      - ../build/wp-content/plugins/rescate-vertical-tools:/var/www/html/wp-content/plugins/rescate-vertical-tools
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  db_data:
  wp_data:
